Fix some set but unused variables
Found by Apple clang version 14.0.3

    .../coordgenlibs/test/coordgenBasicSMILES.h:33:12: error: variable 'idx' set but not used [-Werror,-Wunused-but-set-variable]
        size_t idx = 0;
               ^
    .../coordgenlibs/test/coordgenBasicSMILES.h:33:12: error: variable 'idx' set but not used [-Werror,-Wunused-but-set-variable]
        size_t idx = 0;
               ^
    .../coordgenlibs/test/test_coordgen.cpp:313:9: error: variable 'bondsN' set but not used [-Werror,-Wunused-but-set-variable]
        int bondsN = 0;
            ^